export const presets = {
  empty: {
    map: {
      CommentBox: ['area-left', 2],
      MoveControls: ['drawer', 1],
      HistoryVisualization: ['drawer', 2],
      HistoryStash: ['drawer', 3],
      HistoryControls: ['drawer', 4],
      StartTutorial: ['drawer', 5],
      ScreenSwitcher: ['drawer', 6],
      FrameScaleSlider: ['drawer', 7],
      Inspector: ['drawer', 8],
      ThemeUploadPanel: ['drawer', 9],
      Selectors: ['drawer', 11],
      InformationVisibilitySettings: ['drawer', 12],
      InspectionSettings: ['drawer', 13],
      ColorSettings: ['drawer', 14],
      Palette: ['drawer', 15],
      PickedValue: ['drawer', 16],
      FullscreenToggle: ['drawer', 17],
      NoteBox: ['drawer', 18],
      CursorBehavior: ['drawer', 19],
      RemoveAnnoyingPrefix: ['drawer', 20],
      FullHeightFrameScale: ['drawer', 21],
      ExtraPanelsMenu: ['drawer', 22],
      StylesheetDisabler: ['drawer', 23],
      ImportExportTools: ['drawer', 24],
      ThemesList: ['drawer', 25],
      Filters: ['drawer', 26],
      Xray: ['drawer', 27],
      FrameSizeSettings: ['drawer', 28],
      WebpackHomeInput: ['drawer', 29],
      CustomVariableInput: ['drawer', 30],
      CurrentTheme: ['drawer', 31],
      NameReplacements: ['drawer', 32],
    },
  },
  noTopBar: {
    map: {
      HistoryVisualization: ['area-bottom', 1],
      HistoryControls: ['area-bottom', 2],
      HistoryStash: ['area-bottom', 3],
      NoteBox: ['area-bottom', 4],
      Filters: ['area-bottom', 5],
      ExtraPanelsMenu: ['area-bottom-reverse', 1],
      Selectors: ['area-bottom-reverse', 2],
      FullHeightFrameScale: ['area-bottom-reverse', 3],
      CommentBox: ['area-left', 1],
      Inspector: ['area-left', 2],
      ScreenSwitcher: ['area-left-inner', 1],
      FrameScaleSlider: ['area-left-inner', 2],
      Xray: ['area-left-inner', 3],
      Palette: ['area-left-inner', 4],
      ThemesList: ['area-right', 1],
      StylesheetDisabler: ['area-right', 2],
      ImportExportTools: ['area-right', 3],
      MoveControls: ['drawer', 1],
      InformationVisibilitySettings: ['drawer', 2],
      InspectionSettings: ['drawer', 3],
      ColorSettings: ['drawer', 4],
      CursorBehavior: ['drawer', 5],
      FullscreenToggle: ['drawer', 6],
      ThemeUploadPanel: ['drawer', 7],
      RemoveAnnoyingPrefix: ['drawer', 8],
      StartTutorial: ['drawer', 9],
      PickedValue: ['drawer', 10],
      FrameSizeSettings: ['drawer', 11],
      WebpackHomeInput: ['drawer', 12],
      CustomVariableInput: ['drawer', 13],
      CurrentTheme: ['drawer', 14],
      NameReplacements: ['drawer', 15],
    },
  },
  xrayTopLeft: {
    map: {
      HistoryVisualization: ['area-bottom', 1],
      Palette: ['area-bottom-reverse', 6],
      PickedValue: ['area-bottom', 3],
      NoteBox: ['area-bottom-reverse', 1],
      ExtraPanelsMenu: ['area-bottom-reverse', 2],
      CursorBehavior: ['area-bottom-reverse', 3],
      CommentBox: ['area-left', 2],
      Xray: ['area-left', 3],
      MoveControls: ['area-left', 4],
      Inspector: ['area-left-inner', 1],
      Selectors: ['drawer', 11],
      ColorSettings: ['drawer', 13],
      InformationVisibilitySettings: ['drawer', 12],
      InspectionSettings: ['area-right', 4],
      FullHeightFrameScale: ['area-right', 5],
      ThemesList: ['area-right', 6],
      ImportExportTools: ['area-right', 7],
      HistoryControls: ['area-top', 1],
      HistoryStash: ['area-top', 2],
      Filters: ['area-top', 3],
      FullscreenToggle: ['area-bottom-reverse', 4],
      FrameScaleSlider: ['area-top-reverse', 2],
      ScreenSwitcher: ['area-top-reverse', 3],
      StartTutorial: ['drawer', 10],
      RemoveAnnoyingPrefix: ['area-bottom-reverse', 5],
      NameReplacements: ['drawer', 2],
      FrameSizeSettings: ['drawer', 3],
      CustomVariableInput: ['drawer', 4],
      CurrentTheme: ['drawer', 5],
      ThemeUploadPanel: ['drawer', 6],
      StylesheetDisabler: ['drawer', 8],
      WebpackHomeInput: ['drawer', 9],
    },
  },
};
